export const STEPS = {
  Intro: 0,
  Instructions: 1,
  InstructionsTwo: 2,
  Countdown: 3,
  Block: 4,
};

export const BLOCK_STEPS = {
  Cross: 0,
  Image: 1,
  Rate: 2,
  End: 3,
};

export const KEYCODES = {
  Enter: 13,
};

export const BLOCKS = {
  Adult: {
    1: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    2: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    3: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    4: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    5: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    6: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
  },
  YoungChild: {
    1: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    2: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    3: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    4: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    5: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    6: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
  },
  OldChild: {
    1: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    2: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    3: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    4: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    5: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
    6: [
      '/images/bugs.png',
      '/images/daffy.png',
      '/images/devil.png',
      '/images/sylvester.png',
      '/images/tweety.png',
      '/images/wile.jpeg',
    ],
  },
};
